task :install do
  sh "cd .. && git submodule init"
  sh "cd .. && git submodule update"
  sh "cd WaxSim && xcodebuild install DSTROOT=../../ INSTALL_PATH=/ext/bin"
  sh "cd iCuke && rake"
end

task :default => :install
